apiVersion: v1
kind: Service
metadata:
  name: task-manager-service  # Name of the service
spec:
  type: NodePort  # Exposes the service on a port on each node, making it accessible externally
  selector:
    app: task-manager  # Selects the pods with this label to route traffic to
  ports:
    - protocol: TCP        # Protocol used by the service
      port: 3000           # Cluster-facing port for the service; you can expose 80 in production
      targetPort: 3000     # Port on the container to forward traffic to
      nodePort: 31000      # Fixed external port on the node (range: 30000â€“32767)