apiVersion: v1
kind: Service
metadata:
  name: devops-project-3-service
spec:
  type: LoadBalancer
  selector:
    app: devops-project-3
  ports:
    - protocol: TCP
      port: 80         # Port accessible from the internet
      targetPort: 3000 # Must match the containerPort above
