name: Security & Quality Gate

# so that it triggers on pull requests only
on: [pull_request]

jobs:
 #job: making use of superlinter to scan secrets & bad syntax
  lint-code:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Run Super-Linter # works with almost every language
        uses: github/super-linter@v5
        env:
          VALIDATE_ALL_CODEBASE: false # only checks new code in the PR
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
